-- OPTIONAL hardening for the AI layer: a genuinely read-only role.
-- Run once as ACCOUNTADMIN in Snowsight, then set SNOWFLAKE_AI_ROLE=READER for the app.
-- This is defence-in-depth: even if the SELECT-only validation in app/ai.py were bypassed,
-- AI-generated SQL would physically be unable to modify anything (READER can only SELECT).

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS READER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH      TO ROLE READER;
GRANT USAGE ON DATABASE  SCHOOLS         TO ROLE READER;
GRANT USAGE ON SCHEMA    SCHOOLS.ANALYTICS TO ROLE READER;

GRANT SELECT ON ALL    TABLES IN SCHEMA SCHOOLS.ANALYTICS TO ROLE READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SCHOOLS.ANALYTICS TO ROLE READER;
GRANT SELECT ON ALL    VIEWS  IN SCHEMA SCHOOLS.ANALYTICS TO ROLE READER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA SCHOOLS.ANALYTICS TO ROLE READER;

GRANT ROLE READER TO USER DBT_SVC;   -- same key-pair identity, read-only role for AI queries
GRANT ROLE READER TO ROLE SYSADMIN;  -- manageability
